name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set Docker image tags
        run: |
          if [ -n "${{ env.RELEASE_VERSION }}" ]; then
            echo "IMAGE_TAG=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: server.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-grpc-pingpong/server:${{ env.IMAGE_TAG }}

      - name: Build and Push Client Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: client.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-grpc-pingpong/client:${{ env.IMAGE_TAG }}
